# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

platform :ios do
  desc "Run EssentialApp tests"
  lane :essential_app_tests do
    run_tests(
      scheme: "EssentialApp"
    )
  end

  desc "Build EssentialApp"
  lane :essential_app_build do
    build_app(
      scheme: "EssentialApp"
    )

    api_key = app_store_connect_api_key()

    upload_to_testflight(
      api_key: api_key,
    )
  end
end
