# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

platform :mac do
  desc "Build And Test Platform Independent"
  lane :CI_macOS do
    run_tests(
      scheme: "CI_macOS",
      destination: "platform=macOS",
      clean: true,
      xcargs: 'CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO ONLY_ACTIVE_ARCH=YES'
    )
  end
end

platform :ios do
  desc "Build And Test iOS Platform"
  lane :CI_iOS do
    run_tests(
      scheme: "CI_iOS",
      destination: "platform=iOS Simulator,OS=26.4.1,name=iPhone 17 Pro",
      clean: true,
      xcargs: 'CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO ONLY_ACTIVE_ARCH=YES'
    )
  end

  desc "Build And Test iOS Platform Locally"
  lane :CI_iOS_Local do
    run_tests(
      scheme: "CI_iOS",
      destination: "platform=iOS Simulator,OS=26.4,name=iPhone 17 Pro",
      clean: true,
      xcargs: 'CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO ONLY_ACTIVE_ARCH=YES'
    )
  end

  desc "Build iOS app locally and upload to Testflight"
  lane :Deploy_From_Local do
    build_app(
      scheme: "EssentialApp",
      clean: true
    )

    api_key = app_store_connect_api_key()

    upload_to_testflight(
      api_key: api_key,
    )
  end

  desc "Build iOS app on CI and upload to Testflight"
  lane :Deploy_From_CI do
    setup_ci
    
    match(type: "appstore", readonly: false)

    build_app(
      scheme: "EssentialApp",
      clean: true
    )

    api_key = app_store_connect_api_key(
      key_id: ENV["APP_STORE_CONNECT_API_KEY_KEY_ID"],
      issuer_id: ENV["APP_STORE_CONNECT_API_KEY_ISSUER_ID"],
      key_filepath: ENV["APP_STORE_CONNECT_API_KEY_KEY_FILEPATH"],
      in_house: false
    )

    upload_to_testflight(
      api_key: api_key,
      skip_waiting_for_build_processing: true
    )
  end
end
