name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-and-test:

    runs-on: macos-26

    steps:
    - uses: actions/checkout@v6

    - name: Select Xcode
      run: sudo xcode-select -switch /Applications/Xcode_26.3.0.app

    - name: Build And Test Platform Independent
      run: >
        xcodebuild clean build test
        -project EssentialFeed/EssentialFeed.xcodeproj
        -scheme "CI_macOS"
        -sdk macosx
        -destination "platform=macOS"
        -resultBundlePath PlatformTestResults.xcresult
        CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO ONLY_ACTIVE_ARCH=YES

    - name: Upload Platform Test Results
      uses: actions/upload-artifact@v7
      if: failure() # Ensures logs are uploaded only if tests fail
      with:
        name: platform-test-results
        path: PlatformTestResults.xcresult

    - name: Build And Test iOS Platform Independent
      run: >
        xcodebuild clean build test
        -workspace EssentialApp/EssentialApp.xcworkspace
        -scheme "CI_iOS"
        -sdk iphonesimulator
        -destination "platform=iOS Simulator,OS=26.4,name=iPhone 17 Pro"
        -resultBundlePath iOSPlatformTestResults.xcresult
        CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO ONLY_ACTIVE_ARCH=YES

    - name: Upload iOS Platform Test Results
      uses: actions/upload-artifact@v7
      if: failure() # Ensures logs are uploaded only if tests fail
      with:
        name: ios-platform-test-results
        path: iOSPlatformTestResults.xcresult